### ISSUE TITLE
@imports in SCSS are specified as relative — bug?

### ISSUE THREAD

**Issue by strogonoff** [Hardtack/react-mdcw#38]
Attempt to import an MDC component’s scss within project’s styles.scss results in a file not found.

    @import "~@material/button/mdc-button.scss";

The only way is to import the pre-built CSS:

    @import "~@material/button/dist/mdc.button";

The reason importing SCSS doesn’t work is that _inside_ mdc-button.scss there are imports referring to other MDC’s imports as `"@material/..."`. Note that there’s no `~` character in the front.

Due to the way Webpack resolves imports, you have to tell it that the import is non-relative explicitly by beginning the import with `~`.

Without it, Webpack treats those imports as relative and expects to find `node_modules/@material/button/@material` directory, which does not exist.

It seems obvious that MDC’s authors want those imports to refer to the @material directory that’s directly underneath project’s node_modules. Since Webpack is explicitly mentioned in README it seems that the way it should be is with the `~` in the front to support its way of doing things.

Perhaps I’m missing something, although someone else reported the same problem recently: 

* https://github.com/rails/webpacker/issues/454

**Comment by hardtack** [comment]
I can't understand what the relationship of this issue and library is.
This library does not provide any SCSS / CSS files except document. But, docs project is already configured as MDC's author want.
Could you tell me more details about this issue?

**Comment by strogonoff** [comment]
Thanks, I see now that this issue isn’t relevant to this particular project. Opened by mistake, closing!

**Comment by midnight-wonderer** [comment]
@Hardtack  
I implied that you suggest we should use only the css from `/dist` right?  
Just to make it clear and keep you in the loop this is what we (consumers) are talking about.  
  
We simply wanted to à la carte the css importing to our needs.  
Here, for instance, I wanted to use only the temporary drawer from mdc-drawer  
So I inspect the file  
`node_modules/@material/drawer/mdc-drawer.scss`  
and found out that it is just a bunch of css import.  
```scss
@import "./persistent/mdc-persistent-drawer";
@import "./permanent/mdc-permanent-drawer";
@import "./temporary/mdc-temporary-drawer";
```
I want to import only the last one which located at  
`node_modules/@material/drawer/temporary/mdc-temporary-drawer.scss`  
because thats the only type of drawer I wanted  
  
The defacto (I am not sure if there is any supporting standard) way of importing the file is  
```scss
@import '~@material/drawer/temporary/mdc-temporary-drawer';
```
Now I just successfully imported the file but it won't compile because the file I just imported contains  
```scss
@import "@material/animation/functions";
@import "@material/elevation/mixins";
@import "@material/rtl/mixins";
```
And the compiler goes boom spitting out some error  
```
ERROR in ./node_modules/css-loader??ref--2-2!./node_modules/postcss-loader/lib??ref--2-3!./node_modules/sass-loader/lib/loader.js??ref--2-4!./web_interface/direct_sales/packs/index.scss
Module build failed: 
@import "@material/animation/functions";
^
      File to import not found or unreadable: @material/animation/functions.
Parent style sheet: /home/runner/app/node_modules/@material/drawer/temporary/mdc-temporary-drawer.scss
in /home/runner/app/node_modules/@material/drawer/temporary/mdc-temporary-drawer.scss (line 17, column 1)
```
which sends me here.  
   
Does importing things like this is a fair use case to you?

**Comment by midnight-wonderer** [comment]
Whoops  
I just follow the link sorwee I did not notice that this is just a repo for react binding.  
Not the official mdc repo.  
That's why the OP closed the issue.
