### ISSUE TITLE
[textfield] document how to attach onChange handler

### ISSUE THREAD

**Issue by alanraison** [Hardtack/react-mdcw#44]
Hi. Really enjoying using these components.

I'm now used to using the prop-based pattern for `<input>`s where I have an input element inside a component and I use code such as the following to change the prop value:

```
const Component = ({value,onChange}) => {
  let input;
  return (
    <input ref={ n => input = n } 
      onChange={() => onChange(input.value)}
      value={value}/>
  );
};
```

However, I cannot get a ref for the input field using `<Textfield.Input>`, can you describe the right way to update the application state with the component's value?

Thanks
Alan

**Comment by hardtack** [comment]
Sorry for late response.

I think you are doing wrong with `ref` property.

The type of `ref` property's value is `(ReactInstance | null) => void` and `ReactInstance` is `Component<any, any> | Element`

In the case of
``` typescript
<input ref={(n) => input = n} ... />
```
The type of n will be `HTMLInputElement` since `ref` was defined on HTML component. But, It does not guarantee argument to be and `HTMLElement`. So, you have to use `ReactDOM.findDOMNode` to find a DOM node for `ReactInstance`.

So, you have to use `ref` property like following
``` typescript
const Component = ({value, onChange}) => {
  let input;
  return (
    <input ref={ (n) => input = ReactDOM.findDOMNode(n) } 
      onChange={() => onChange(input.value)}
      value={value}/>
  );
};
```

But, this would be better (I added some TypeScript stuff)

``` typescript
class Component extends React.Component<{value?: boolean}, {}> {
  public render() {
    return (
        <input onChange={this.handleInputChange} value={this.props.value} />
    );
  }

  private handleInputChange = (e: React.FormEvent<HTMLInputElement>) => {
    const value = e.target.value;
    ...
  };
}
```

You can also use `Textfield.Input` component same as above.
In that case, the actual type for argument of `ref` function will be instance of `Textfield.Input` class.
